<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/daterangepicker/daterangepicker.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/icheck-bootstrap/icheck-bootstrap.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/jqvmap/jqvmap.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/datatables-responsive/css/responsive.bootstrap4.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/toastr/toastr.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/pace-progress/themes/black/pace-theme-flat-top.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/select2/css/select2.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css'}}">
<link rel="stylesheet" href="{{asset('vendor/adminPanel/plugins/fullcalendar/main.css')}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/panel/dist/css/adminlte.min.css'}}">
<link rel="stylesheet" href="{{asset('vendor/adminPanel/plugins/summernote/summernote-bs4.css')}}">
<link rel="stylesheet" href="{{'https://site-assets.fontawesome.com/releases/v6.1.1/css/all.css'}}">
<link rel="stylesheet" href="{{'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700'}}">
